### ISSUE TITLE
Enhancement: Responsive design

### ISSUE THREAD

**Issue by hbayyavarapu** [rlopez0689/OrgChartJit#2]
A responsive version of this would be of great help.

**Comment by rlopez0689** [comment]
Thanks for your suggestion. I added the touch events. So you can use it in mobile devices. With this feature you consider it responsive or you were thinking in something else?

Greetings

**Comment by hbayyavarapu** [comment]
I'm using this in the portlet, the portlet only occupies 30% of the available space width wise, the plugin seems to create a horizontal scrollbar. I would be really nice, if it can stack depending on the available space.

**Comment by rlopez0689** [comment]
In the demo if you resize the window, the diagram i`t always in the center and with the width of the window space. Also it have the zooming and the touch event for better navigation in mobile devices. I don't know what else to make to make it more responsive and not to sacrifice the clarity of the diagram.

**Comment by hbayyavarapu** [comment]
I'm still understanding your plugin. I have question, I need to give fixed
height for the div. If the chart is big, I see the tree is been chopped off
from view. How can I dynamically increase the height based on the selected
node, or subtree nodes. It would really helpful.

Thanks!

**Comment by rlopez0689** [comment]
I'm not sure if i understand. Can you please be more specific or if you have the example it will be very helpful.

If you want to resize dynamically the canvas, you can use: st.canvas.resize(1200, 1200)

**Comment by hbayyavarapu** [comment]
#infovis {

```
width:100%;

height:500px;

margin:auto;

overflow:hidden;

background: rgb(45,45,46);
```

}

<div id="infovis">
</div>

Here infovis is set to 500px in height. Now my chart is bigger that it fits
in the 500px height. Assuming, the total height required is 800px to fit
properly, rest of the chart is not visible in the div, because it exceeded
the height. In this case, how I can increase the height of the div to 800px
or so that the div re sizes as the chart is increased or decreased based on
selected nodes.

Does it make sense ?

**Comment by rlopez0689** [comment]
I really don't understand the problem, you can increase the height of the div(infovis) with simple javascript. 
Or if your problem is more complex you can use the functions of jit js in the canvas.
Have you try with the scale function of canvas? With that function you can make the chart fit in the div. 

http://philogb.github.io/jit/static/v20/Docs/files/Core/Canvas-js.html#Canvas.scale

**Comment by hbayyavarapu** [comment]
What I mean is auto resizing of the div, based on the chart height, instead
of explicitly setting height.

**Comment by rlopez0689** [comment]
Ohhh ok. I understand. I don't think it can have and auto resize. Because the chart depends on the height of the div. Maybe it can be done by resizing every time the graph changes. I will try to think of something. If you think of something please let me know.

Regards and thank you for your interest.

**Comment by hbayyavarapu** [comment]
Hi,

I have this function to resize, but didn't understand how to resize the div
everytime the graph changes. Any ideas ?

I had this inside, may be this is not the right place to make it work. It
was going into infinite loop or something.

jit.ST({
onComplete: function() {
// resize(config);
}
});

function resize(config) {
 //count nodes
 var count = 0,
node_height = config.st.graph.Node.height;

 $jit.Graph.Util.eachNode(config.st.clickedNode, function(n) { count++; });

 //calculate new height
 var height = count \* node_height + 10;

 //resize the canvas
 config.st.canvas.resize(0, height, false);
 //re-select the node to replot the tree
 config.st.select(config.st.clickedNode);

}
